sweetening/bike-match

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
I created a home page with a simple bootstrap navbar and added the class title-which applies the red color to text
> created a very rough home page

- app/controllers/bikes_controller.rb
- app/views/bikes/show.html.erb
- config/routes.rb
I have created the show method, a show page and the show routes for the bikes
> created bikes show page and routes

- app/controllers/bikes_controller.rb
- app/views/pages/index.html.erb
- config/routes.rb
- did the index (list of all bikes) in the routes
- in the controller (method)
- in the view
> list_all_bikes

- app/controllers/bikes_controller.rb
- app/models/bike.rb
- app/views/bikes/_form.html.erb
- app/views/bikes/new.html.erb
- app/views/layouts/application.html.erb
- config/puma.rb
- config/routes.rb
- db/migrate/20200526123956_change_column_name.rb
- db/schema.rb
Made the form for adding a bike
> Add new bike

- app/views/bikes/index.html.erb
> add Index html

- app/views/bikes/show.html.erb
I fixed in the bike show page where it said @bike.type to @bike.category
> fixed show page

- app/controllers/bikes_controller.rb
- app/controllers/bookings_controller.rb
- test/controllers/bookings_controller_test.rb
I made the destroy and the bookings controller
> destroy method bikes and bookings controller

- app/controllers/bookings_controller.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
- config/routes.rb
- db/migrate/20200526144225_remove_date_from_bookings.rb
- db/schema.rb
added a new and create method for booking, created the views and added the routes, also deleted date from the bookings table
> new, create for booking

- app/controllers/bookings_controller.rb
- app/views/bikes/show.html.erb
- app/views/bookings/edit.html.erb
- config/routes.rb
Completed the edit booking form
> Edit booking

- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- config/routes.rb
I made the booking show controller part and the view. also I added the destroy route to bike
> booking-show-controller-and-view-destroy-route-bike

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- config/routes.rb
*all bookings and delete function for controller
*view
*route
> all bookings and delete function

- app/views/devise/registrations/new.html.erb
just added some bootstrap to the sign up button
> added some style to the sign up page

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/bikes/index.html.erb
- app/views/bikes/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
created links that worked on homepage, navbar, and show page. Fixed show page front-end, fixed a few pages so that they were in containers and not touching the sides of the website.
> Show page frontend

- app/assets/stylesheets/pages/_index.scss
- app/views/bikes/index.html.erb
> index cards

- Gemfile
- Gemfile.lock
- db/seeds.rb
> seeds are seeded

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/controllers/bookings_controller.rb
- app/views/bikes/edit.html.erb
- app/views/bikes/index.html.erb
- app/views/bikes/new.html.erb
- app/views/bikes/show.html.erb
- app/views/bookings/new.html.erb
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
fixed the grid on both the dashboard and the bike page also the pesky sign out problem
> fixed the grids and some other front end

- app/controllers/bikes_controller.rb
- app/models/bike.rb
- app/views/bikes/show.html.erb
- app/views/dashboard/index.html.erb
- config/routes.rb
added the delete btn and action to bike
> added the delete btn and action to bike

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/bikes_controller.rb
- app/models/bike.rb
- app/views/bikes/_form.html.erb
- app/views/bikes/index.html.erb
- app/views/bikes/show.html.erb
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20200528115111_create_active_storage_tables.active_storage.rb
- db/migrate/20200528120342_remove_image_url_from_bikes.rb
- db/migrate/20200528120439_add_photo_to_bikes.rb
- db/schema.rb
- db/seeds.rb
Made an image upload function on the form
> Image upload

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/show.scss
- app/controllers/bookings_controller.rb
- app/views/bikes/index.html.erb
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/dashboard/index.html.erb
Total price and booking confirmation
> total price and confirmation

- app/assets/stylesheets/pages/show.scss
- app/views/bookings/show.html.erb
Booking confirmation, total price and the button linked to the dashboard
> total price and Booking confirmation

- app/views/bikes/index.html.erb
- app/views/bikes/show.html.erb
- app/views/dashboard/index.html.erb
> started pic changes

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/views/bikes/_form.html.erb
- app/views/bikes/edit.html.erb
- app/views/bikes/index.html.erb
- app/views/bikes/new.html.erb
- app/views/bikes/show.html.erb
- app/views/bookings/edit.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- app/views/dashboard/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
improved the carousel and the navbar and unified the buttons
> frontend fun

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/plugins/init_mapbox.js
- app/views/bikes/index.html.erb
- package.json
- yarn.lock
map index page in sticky position
> map index page in sticky position
